export const selectSearchId = state => state.id.searchId
export const selectTickets = state => state.id.tickets
export const selectLoading = state => state.id.loading
export const selectSortButton = state => state.sort.sortButton
export const selectFilterAll = state => state.filter.all
export const selectFilterNone = state => state.filter.noneStop
export const selectFilterOne = state => state.filter.oneStop
export const selectFilterTwo = state => state.filter.twoStops
export const selectFilterThree = state => state.filter.threeStops
export const selectDisplayedTicketsCount = state => state.more.displayedTicketsCount
